Conjunto/config/routes.rb
Rails.application.routes.draw do

   root 'towers#index'

   resources :towers do
   resources :apartments do
   resources :people
 end
end 

end

Conjunto/app/models/apartment.rb
class Apartment < ActiveRecord::Base
	belongs_to :tower
	has_many :people
end

Conjunto/app/models/person.rb
class Person < ActiveRecord::Base
	belongs_to :apartment
end

Conjunto/app/models/tower.rb
class Tower < ActiveRecord::Base
	has_many :apartments
end

Conjunto/app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController

	def index
		@tower = Tower.find(params[:tower_id])
		@apartments = @tower.apartments
	end

	def new
		@tower = Tower.find(params[:tower_id])
		@apartment = @tower.apartments.new
	end

	def create
		@tower = Tower.find(params[:tower_id])
		@apartment = @tower.apartments.new(apartment_params)
		@apartment.save
		redirect_to tower_apartments_path
	end

	def edit
		@tower = Tower.find(params[:tower_id])
		@apartment = @tower.apartments.find(params[:id])
	end

	def show
		@tower = Tower.find(params[:tower_id])
		@apartment = @tower.apartment.find(params[:id])
		@apartment_nuevo = Apartment.new
	end

	def update
		@tower = Tower.find(params[:tower_id])
		@apartment = @tower.apartment.find(params[:id])
		@apartment.update(apartment_params)
		redirect_to tower_apartments_path
	end

	def destroy
		@tower = Tower.find(params[:tower_id])
		@apartment = @tower.apartment.find(params[:id])
		@apartment.destroy
		redirect_to tower_apartments_path
	end

	def apartment_params
		params.require(:apartment).permit(:name, :tower_id, :floor)
	end

end
 

Conjunto/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Conjunto/app/controllers/people_controller.rb
class PeopleController < ApplicationController

before_action :nested_routes

	 def nested_routes
	 	@tower = Tower.find(params[:tower_id]) 
	 	@apartment = @tower.apartments.find(params[:apartment_id])   
	 end

	def index
		@people = @apartment.people.all 		 
	end

	def new
		@person = @apartment.people.new
	end 

	def edit 
		@person = @apartment.people.find(params[:id])  
	end

	def create
		@person = @apartment.people.new(person_params)
		@person.save
		redirect_to tower_apartment_people_path
	end

	def destroy
		@person = @apartment.people.find(params[:id])
		@person.destroy
		redirect_to tower_apartment_people_path
	end 

	def update
		@person = @apartment.people.find(params[:id])
		@person.update(person_params) 
		redirect_to tower_apartment_people_path
	end

	def person_params
		params.require(:person).permit(:name, :di, :tower_id, :apartment_id)
	end

end

Conjunto/app/controllers/towers_controller.rb
class TowersController < ApplicationController

	def index
		@towers = Tower.all
	end

	def new
		@tower = Tower.new
	end

	def create
		@tower = Tower.new(tower_params)
		@tower.save
		redirect_to towers_path
	end

	def edit
		@tower = Tower.find(params[:id])
	end

	def show
		@tower = Tower.find(params[:id])
		@tower_new = Tower.new
	
	end

	def update
    @tower = Tower.find(params[:id])
    @tower.update(tower_params)
    redirect_to towers_path
  end

  def destroy
    @tower = Tower.find(params[:id])
    @tower.destroy
    redirect_to towers_path
  end

  def tower_params
        params.require(:tower).permit(:name, :vigilant)
  end

end

Conjunto/app/helpers/apartments_helper.rb
module ApartmentsHelper
end

Conjunto/app/helpers/application_helper.rb
module ApplicationHelper
end

Conjunto/app/helpers/people_helper.rb
module PeopleHelper
end

Conjunto/app/helpers/towers_helper.rb
module TowersHelper
end

Conjunto/app/views/apartments/_form.html.erb
<%= form_for [@tower, @apartment] do |a| %>

<div>
	<%= a.label :name %>
	<%= a.text_field :name %>
</div>

<div>
	<%= a.label :floor %>
	<%= a.text_field :floor %>
</div>

<%= a.submit "Crear apartamento" %>

<% end %>

Conjunto/app/views/apartments/edit.html.erb
<h1>Editar apartamento</h1>

<%= render partial: "form", locals: {apartment: @apartment} %>

Conjunto/app/views/apartments/index.html.erb
<h1>Lista de apartamentos</h1>

<%= link_to "Agregar apartamento", new_tower_apartment_path(@tower, @apartment) %>

<ol>
	<% @apartments.each do |apartment| %>
	<li>
		<%= apartment.name %>
		<%= apartment.floor %>
		<%= link_to "Editar", edit_tower_apartment_path(@tower, apartment) %>
		<%= link_to "Eliminar", tower_apartment_path(@tower, apartment), method: :delete, data: {confirm: "Estás seguro?"} %>
		<%= link_to 'Ver residentes', tower_apartment_people_path(@tower, apartment) %>
		
	</li>

	<% end %>

</ol>

<%= link_to "Volver a inicio", root_path %>

Conjunto/app/views/apartments/new.html.erb
<h1>Crear nuevo apartamento</h1>

<%= render partial: "form", locals: {apartment: @apartment} %>

Conjunto/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Conjunto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Conjunto/app/views/people/_form.html.erb
<%= form_for [@tower, @apartment, @person] do |p| %>

<div>
	<%= p.label :name %>
	<%= p.text_field :name %>
</div>

<div>
	<%= p.label :di %>
	<%= p.text_field :id %>
</div>

<%= p.submit "Crear residente" %>

<% end %>

<%= link_to "Volver a inicio", root_path %>

Conjunto/app/views/people/edit.html.erb
<h1>Editar residente</h1>

<%= render partial: "form", locals: {person: @person} %>

Conjunto/app/views/people/index.html.erb
<h1>Lista de residentes</h1>

<%= link_to "Agregar residente", new_tower_apartment_person_path %>

<ol>
	<% @people.each do |person| %>
	<li>
		<%= person.name %>
		<%= person.di %>
		<%= link_to "Editar", edit_tower_apartment_person_path(@tower, @apartment, person) %>
		<%= link_to "Eliminar", tower_apartment_people_path(@tower, @apartment, person), method: :delete, data: {confirm: "Estás seguro?"} %>
		
	</li>

	<% end %>

</ol>

<%= link_to "Volver a inicio", root_path %>

Conjunto/app/views/people/new.html.erb
<h1>Crear residente</h1>

<%= render partial: "form", locals: {person: @person} %>

Conjunto/app/views/towers/_form.html.erb
<%= form_for tower do |t| %>

<div>
	<%= t.label :name %>
	<%= t.text_field :name %>
</div>

<div>
	<%= t.label :vigilant %>
	<%= t.text_field :vigilant %>
</div>

<%= t.submit "Crear torre" %>

<% end %>

<%= link_to "Volver a inicio", root_path %>

Conjunto/app/views/towers/edit.html.erb
<h1>Actualizar torre</h1>

<%= render partial: "form", locals: {tower: @tower} %>

Conjunto/app/views/towers/index.html.erb
<h1>Conjunto residencial</h1>

<%= link_to "Agregar torre", new_tower_path %>

<ol>
	<% @towers.each do |tower| %>
	<li>
		<%= tower.name %>
		<%= tower.vigilant %>
		<%= link_to "Editar", edit_tower_path(tower) %>
		<%= link_to "Eliminar", tower_path(tower), method: :delete, data: {confirm: "Estás seguro?"} %>
		<%= link_to 'Ver apartamentos', tower_apartments_path(tower) %>
	</li>

	<% end %>

</ol>

Conjunto/app/views/towers/new.html.erb
<h1>Crear torre</h1>

<%= render partial: "form", locals: {tower: @tower} %>